### ISSUE TITLE
a small bug performing calibration

### ISSUE THREAD

**Issue by CaesarTheFox** [dicengine/dice#106]
when I performed calibration, because the file name is too long, the buttons and file names are at wrong location. And it is difficult to find the matching button for certain image pair.

I can use a shorter name now, but I guess it is not difficult to solve this problem.
![1](https://user-images.githubusercontent.com/46268648/53124116-81a25280-3552-11e9-9a93-3a26fc458837.png)
![2](https://user-images.githubusercontent.com/46268648/53124117-81a25280-3552-11e9-9396-887def022ec7.png)

**Comment by dicengine** [comment]
Thanks for letting us know about this. We’ll try to get it fixed in the next release.

-Dan

On Feb 20, 2019, at 2:03 PM, CaesarTheFox <notifications@github.com<mailto:notifications@github.com>> wrote:


when I performed calibration, because the file name is too long, the buttons and file names are at wrong location. And it is difficult to find the matching button for certain image pair.

I can use a shorter name now, but I guess it is not difficult to solve this problem.
[1]<https://user-images.githubusercontent.com/46268648/53124116-81a25280-3552-11e9-9a93-3a26fc458837.png>
[2]<https://user-images.githubusercontent.com/46268648/53124117-81a25280-3552-11e9-9396-887def022ec7.png>
