### ISSUE TITLE
displacement jump tolerance parameter adjustment failure

### ISSUE THREAD

**Issue by WAH0731** [dicengine/dice#107]
I was told before about running DICe from command line, which I did but found some problem today. I did two analysis with the same 600 pictures and same ROI and subset size and everything. Only the first time I ran it from GUI and the second time I added "<Parameter name="disp_jump_tol" type="double" value="500.0" />?" into the params.xml and ran it from command line.

The change of disp_jump_tol is showned in the output content in command, so it worked. But what's strange is that the whole analysis time of the first time is 4min 20sec, and of the second time is 4min 13sec.

which makes no sense since the searching area is much larger in the second time as the disp_jump_tol is raised, the analysis should cost a magnificent longer time.

Maybe this line I added didn't really work. I think it will be a good idea to put the searching range as a set in GUI, just like step size or subset size. 

It would make it possible to analysis high speed rotation issue if this problem can be solved。

**Comment by dicengine** [comment]
Hi Huang,

You shouldn’t see much difference in the timing due to changing the displacement jump tolerance. The default initialization scheme in DICe does not do a search, it either uses feature matching or the previous solution as the initial guess. The jump tolerance is used rather to make sure you don’t get a nonsense solution if the algorithm fails. For example, you may be expecting that all the motion from frame to frame to be less than 10 pixels, so you would set the displacement jump tolerance to 10pixels and if this tolerance is exceeded DICe will mark this as a failed subset. It has no impact on an initial search (which is not done anyway in the default case).

I had a hard time downloading your images from the last email. If you have a good set of images to test with for the high speed rotations case, let me know. I’d be happy to see if I can get it to work and what settings to use.

Thanks,
Dan



On Mar 6, 2019, at 4:40 AM, WAH0731 <notifications@github.com<mailto:notifications@github.com>> wrote:


I was told before about running DICe from command line, which I did but found some problem today. I did two analysis with the same 600 pictures and same ROI and subset size and everything. Only the first time I ran it from GUI and the second time I added "?" into the params.xml and ran it from command line.

The change of disp_jump_tol is showned in the output content in command, so it worked. But what's strange is that the whole analysis time of the first time is 4min 20sec, and of the second time is 4min 13sec.

which makes no sense since the searching area is much larger in the second time as the disp_jump_tol is raised, the analysis should cost a magnificent longer time.

Maybe this line I added didn't really work. I think it will be a good idea to put the searching range as a set in GUI, just like step size or subset size.

It would make it possible to analysis high speed rotation issue if this problem can be solved。

**Comment by WAH0731** [comment]
I see, thanks for explaining
