### ISSUE TITLE
Stereo ROI problems

### ISSUE THREAD

**Issue by shazryz** [dicengine/dice#120]
Hi there,
I am just wondering why when I set up ROI for the stereo analysis, the Paraview image cannot be rotated, and the final image appears as if it is a 2D analysis. I did follow the video posted on youtube, first without setting any ROI and then with ROI, the resulting images are different, with the first one can be rotated and the later being 2D. Is there anything that I am missing when I set up the ROI because I did the same procedure both analysis. Thank you.

**Comment by dicengine** [comment]
Hi,

Are you able to post an image or two that shows what you’re describing below? I’m not sure I completely grasp what the issue is.
If you’re able to share your results files for both cases, that would help a lot too but I realize that’s not always possible.

-Dan


On May 15, 2019, at 8:39 AM, shazryz <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi there,
I am just wondering why when I set up ROI for the stereo analysis, the Paraview image cannot be rotated, and the final image appears as if it is a 2D analysis. I did follow the video posted on youtube, first without setting any ROI and then with ROI, the resulting images are different, with the first one can be rotated and the later being 2D. Is there anything that I am missing when I set up the ROI because I did the same procedure both analysis. Thank you.

**Comment by shazryz** [comment]
[DICe_solution_0.txt](https://github.com/dicengine/dice/files/3183183/DICe_solution_0.txt)
[DICe_solution_0.txt](https://github.com/dicengine/dice/files/3183186/DICe_solution_0.txt)

The first one is the one without ROI and the second one is the one with ROI.

**Comment by dicengine** [comment]
Looks like you are getting NaNs in the second output file "#QNB" for the model coordinates. Something must be getting screwed up in the triangulation. Are you able to send me the input files so I can try to recreate your problem? I don't need the full image set, but at least the images for the first time step, the input.xml file, params.xml, and subset_defs.txt.

**Comment by shazryz** [comment]
[input.xml](https://github.com/dicengine/dice/files/3183267/input.xml)
[params.xml](https://github.com/dicengine/dice/files/3183268/params.xml)
[subset_defs.txt](https://github.com/dicengine/dice/files/3183275/subset_defs.txt)
[subset_locs.txt](https://github.com/dicengine/dice/files/3183276/subset_locs.txt)

**Comment by dicengine** [comment]
Can you post the reference images for both cameras?

**Comment by shazryz** [comment]
![right_projected_to_left_final](https://user-images.githubusercontent.com/50669091/57794051-00e19580-7700-11e9-8a23-13506e555a8a.jpeg)
![right_projected_to_left_initial](https://user-images.githubusercontent.com/50669091/57794052-00e19580-7700-11e9-9699-e2a7f6c476a2.jpeg)
![right_projected_to_left_proj_opt](https://user-images.githubusercontent.com/50669091/57794053-00e19580-7700-11e9-9b40-063336c2d57e.jpeg)
![fm_initializer_0](https://user-images.githubusercontent.com/50669091/57794055-00e19580-7700-11e9-820d-7e7afed27082.png)
![fm_projective_trans_0](https://user-images.githubusercontent.com/50669091/57794056-00e19580-7700-11e9-9669-4adc52b53065.png)
![right_projected_to_left_color](https://user-images.githubusercontent.com/50669091/57794057-017a2c00-7700-11e9-9d61-18bec21e7f53.jpeg)
![right_projected_to_left_diff](https://user-images.githubusercontent.com/50669091/57794058-017a2c00-7700-11e9-95a5-a58f2b11b3f1.jpeg)

**Comment by shazryz** [comment]
[right_projected_to_left_diff](https://user-images.githubusercontent.com/50669091/57794248-76e5fc80-7700-11e9-83c7-3144414c9562.jpeg)
[right_projected_to_left_final](https://user-images.githubusercontent.com/50669091/57794249-76e5fc80-7700-11e9-97cc-7d8dda421e47.jpeg)
[right_projected_to_left_initial](https://user-images.githubusercontent.com/50669091/57794250-777e9300-7700-11e9-857a-979efc772343.jpeg)
[right_projected_to_left_proj_opt](https://user-images.githubusercontent.com/50669091/57794251-777e9300-7700-11e9-93ca-95f7ce325953.jpeg)
[fm_initializer_0](https://user-images.githubusercontent.com/50669091/57794252-777e9300-7700-11e9-8c67-91cdd082591f.png)
[fm_projective_trans_0](https://user-images.githubusercontent.com/50669091/57794254-777e9300-7700-11e9-9e5f-8b1dc669f972.png)
[right_projected_to_left_color](https://user-images.githubusercontent.com/50669091/57794255-777e9300-7700-11e9-975b-3a0ed9a57455.jpeg)

**Comment by dicengine** [comment]
Thanks! I'll take a look and see what I can find.

**Comment by shazryz** [comment]
Sorry, I can't seem to upload the images properly.

**Comment by shazryz** [comment]
Are there any updates regarding this matter?

**Comment by dicengine** [comment]
Looks like the uploads failed for your input files and images, if I click the links to your files I get a 'Not Found' error. Can you either try to upload them again or send them to me at dzturne@sandia.gov? I don't need any of the images linked above, but rather the actual .tiff input images used

**Comment by dicengine** [comment]
From @shazryz :
One more thing regarding the ROI, I am currently analyzing one of the results and the images have a lot of noises and I thought the ROI could solve it. But the ROI seems to unable to detect the ROI and the console stated that the noises are the reason, despite setting the ROI on the reference image. I'm not too sure if I'm setting the ROI wrongly, because I only relied on the youtube videos that are available.

**Comment by dicengine** [comment]
I'm not sure I understand your comment above, but I ran your example above on my machine (a mac) and it ran fine and doesn't seem to be impacted by having or not having an ROI. I haven't been able to test it on windows, but I will let you know if I can recreate the issue there.

**Comment by shazryz** [comment]
Sounds good. I really appreciate your help. Thank you!

Sincerely,

AHMAD SHAZRYZ AZNI
Undergraduate Student
University of Alberta, 2020
BSc. Petroleum Engineering
azni@ualberta.ca | 587-936-3728

**Comment by shazryz** [comment]
[image: image.png]
[image: image.png]
So, did you get this result on Paraview after you ran the code on Mac? This
is the result I got and it cant be rotated. I just want to double check
with you. The 2nd picture is the one without the ROI, and the image can be
rotated.

**Comment by dicengine** [comment]
The problem with paraview is that there are a bunch of NaNs in the results file. And the NaNs are in the model coordinates which ParaView uses to create the model view, so it’s not surprising that ParaView is having problems.

On May 16, 2019, at 3:41 PM, shazryz <notifications@github.com<mailto:notifications@github.com>> wrote:

[image: image.png]
[image: image.png]
So, did you get this result on Paraview after you ran the code on Mac? This
is the result I got and it cant be rotated. I just want to double check
with you. The 2nd picture is the one without the ROI, and the image can be
rotated.

**Comment by shazryz** [comment]
I see. So is there a way to not read the result besides using Paraview?

**Comment by shazryz** [comment]
Hello there,
May I get any updates regarding this matter? Do I have to physically crop my images to get the ROI instead of using the ROI in the software for the NaNs not to show up in the results file?

**Comment by dicengine** [comment]
I’m not sure where the NaNs are coming from. I haven’t been able to reproduce the problem. One thing you could try is a simpler ROI, that doesn’t have so many points. See if that produces the same NaNs in the output.


On May 21, 2019, at 8:44 AM, shazryz <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello there,
May I get any updates regarding this matter? Do I have to physically crop my images to get the ROI instead of using the ROI in the software for the NaNs not to show up in the results file?

**Comment by shazryz** [comment]
I was able to use the ROI function after I cropped the photos so that the noises are left out. After simplifying the ROI, I was able to rotate the image on Paraview. So, I'm guessing it is working now. However, I still find that the ROI is useless when it comes to photo with high noise level. The first image is the original photo while the second one is the cropped version of it. I could only run the software after cropping the photo. Hence, I do find the ROI to be useless in my analysis. If I were to use the ROI in the first image, the calculation failed after the calibration was validated. The console mentioned it is due to the noise in the first image.
![image](https://user-images.githubusercontent.com/50669091/58265692-6a375900-7d3d-11e9-8fa2-c7daf86ad5e7.png)
![image](https://user-images.githubusercontent.com/50669091/58265726-7f13ec80-7d3d-11e9-8513-83877b5cfc53.png)
