### ISSUE TITLE
Linking Error on DICe_TrackingMovieMaker

### ISSUE THREAD

**Issue by haemishkyd** [dicengine/dice#136]
I am trying to compile DICE under Ubuntu 18.04LTS.
I have followed the instructions [here](http://dicengine.github.io/dice/index.html) but I have the following error:

`/usr/bin/ld: ~/Masters/CodeRepo/dice/build/install/lib/libdiceutils.a(DICe_ImageIO.cpp.o): undefined reference to symbol '_ZN2cv7imwriteERKNS_6StringERKNS_11_InputArrayERKSt6vectorIiSaIiEE'
~/Masters/CodeRepo/opencv-3.2.0/build/install/lib/libopencv_imgcodecs.so.3.2.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
tools/CMakeFiles/DICe_TrackingMovieMaker.dir/build.make:145: recipe for target 'bin/DICe_TrackingMovieMaker' failed
make[2]: *** [bin/DICe_TrackingMovieMaker] Error 1`

As you can see from the error the linker can't seem to find **imwrite** in the **opencv** library **imgcodecs**. 

Both Trilinos 12.4.2  and OpenCV 3.2.0 compiled without error and I have used the provided scripts for all compilation.
The digging that I have done suggests that there is something wrong with the library includes or something along those lines. This makes sense but I am not sure what I could change. I created a virtual machine to build this on so there is no other software that could really be interfering. 

I would appreciate if a theory or two could be thrown my way because I am all out of ideas with regards to how to resolve this. The only thing I can still try is to compile under 16.04LTS but that seems like a step backwards considering it is the previous LTS version.

**Comment by dicengine** [comment]
I haven’t built DICe under Ubuntu 18.04LTS and I’m not sure I have any good ideas as to the error message below, but you could always disable the building of the tracking movie maker. It’s only used for viewing output.

In dice/tools/CMakeLists.txt lines 138 - 148 comment out any reference to them movie maker.

You could always come back to building this later if you need to visualize the tracking.

On Aug 9, 2019, at 6:37 AM, Haemish Kyd <notifications@github.com<mailto:notifications@github.com>> wrote:


I am trying to compile DICE under Ubuntu 18.04LTS.
I have followed the instructions here<http://dicengine.github.io/dice/index.html> but I have the following error:

/usr/bin/ld: ~/Masters/CodeRepo/dice/build/install/lib/libdiceutils.a(DICe_ImageIO.cpp.o): undefined reference to symbol '_ZN2cv7imwriteERKNS_6StringERKNS_11_InputArrayERKSt6vectorIiSaIiEE' ~/Masters/CodeRepo/opencv-3.2.0/build/install/lib/libopencv_imgcodecs.so.3.2.0: error adding symbols: DSO missing from command line collect2: error: ld returned 1 exit status tools/CMakeFiles/DICe_TrackingMovieMaker.dir/build.make:145: recipe for target 'bin/DICe_TrackingMovieMaker' failed make[2]: *** [bin/DICe_TrackingMovieMaker] Error 1

Both Trilinos 12.4.2 and OpenCV 3.2.0 compiled without error and I have used the provided scripts for all compilation.
The digging that I have done suggests that there is something wrong with the library includes or something along those lines. This makes sense but I am not sure what I could change. I created a virtual machine to build this on so there is no other software that could really be interfering.

I would appreciate if a theory or two could be thrown my way because I am all out of ideas with regards to how to resolve this. The only thing I can still try is to compile under 16.04LTS but that seems like a step backwards considering it is the previous LTS version.

**Comment by haemishkyd** [comment]
Thanks. I tried your suggestion but it seems that there is a problem in general with the system linking the opencv libraries. I have now just got other issues with other opencv functions. I will investigate. I have now created an Ubuntu 16.04 LTS virtual machine and have followed the instructions on that machine and I still have this problem. I am a bit lost but will continue to investigate and come back with anything I find.

**Comment by haemishkyd** [comment]
I have attached the output of running **do-dice-cmake** in the hope that something in it highlights what my problem might be. I am starting to think it is a problem with the order that the various libraries are being linked but I am not sure why that would be different from the norm unless I am missing something that I should have. I would appreciate any input.
[cmake_output.txt](https://github.com/dicengine/dice/files/3495555/cmake_output.txt)

**Comment by haemishkyd** [comment]
I seem to have found the problem but now I am not sure where in the cmake rabbit hole to fix it. It seems the problem is that the diceutils package needs the symbols for imgcodecs (from opencv) to be linked _after_ instead of or as well as before. The command to link DICe_TrackingMovieMaker is long but contains:
 `/home/haemish/Masters/CodeRepo/opencv-3.2.0/build/install/lib/libopencv_imgcodecs.so.3.2.0 /home/haemish/Masters/CodeRepo/opencv-3.2.0/build/install/lib/libopencv_imgproc.so.3.2.0 /home/haemish/Masters/CodeRepo/opencv-3.2.0/build/install/lib/libopencv_core.so.3.2.0 -ldiceutils`
if I manually change this to 
`/home/haemish/Masters/CodeRepo/opencv-3.2.0/build/install/lib/libopencv_imgcodecs.so.3.2.0 /home/haemish/Masters/CodeRepo/opencv-3.2.0/build/install/lib/libopencv_imgproc.so.3.2.0 /home/haemish/Masters/CodeRepo/opencv-3.2.0/build/install/lib/libopencv_core.so.3.2.0 -ldiceutils /home/haemish/Masters/CodeRepo/opencv-3.2.0/build/install/lib/libopencv_imgcodecs.so.3.2.0` 
in the **link.txt** it then links correctly. This is then true for all subsequent link errors.

My question is - where in the cmake infrastructure for this project would I do this. I have tried to find it but I haven't had much luck. Any thoughts would be appreciated.

**Comment by dicengine** [comment]
Have you tried manually adding it to the linker flags in your do-camke script? I don’t know how to fix the order in cmake or if it’s possible.

On Aug 16, 2019, at 10:08 AM, Haemish Kyd <notifications@github.com<mailto:notifications@github.com>> wrote:


I seem to have found the problem but now I am not sure where in the cmake rabbit hole to fix it. It seems the problem is that the diceutils package needs the symbols for imgcodecs (from opencv) to be linked after instead of or as well as before. The command to link DICe_TrackingMovieMaker is long but contains:
/home/haemish/Masters/CodeRepo/opencv-3.2.0/build/install/lib/libopencv_imgcodecs.so.3.2.0 /home/haemish/Masters/CodeRepo/opencv-3.2.0/build/install/lib/libopencv_imgproc.so.3.2.0 /home/haemish/Masters/CodeRepo/opencv-3.2.0/build/install/lib/libopencv_core.so.3.2.0 -ldiceutils
if I manually change this to
/home/haemish/Masters/CodeRepo/opencv-3.2.0/build/install/lib/libopencv_imgcodecs.so.3.2.0 /home/haemish/Masters/CodeRepo/opencv-3.2.0/build/install/lib/libopencv_imgproc.so.3.2.0 /home/haemish/Masters/CodeRepo/opencv-3.2.0/build/install/lib/libopencv_core.so.3.2.0 -ldiceutils /home/haemish/Masters/CodeRepo/opencv-3.2.0/build/install/lib/libopencv_imgcodecs.so.3.2.0
in the link.txt it then links correctly. This is then true for all subsequent link errors.

My question is - where in the cmake infrastructure for this project would I do this. I have tried to find it but I haven't had much luck. Any thoughts would be appreciated.

**Comment by haemishkyd** [comment]
I seem to have resolved the problem. 
In the CmakeLists.txt under dice/src/ line 143 the diceutils and ${OpenCV_LIBRARIES} need to swap around. Doing this allowed the entire suite of software to compile correctly.

Thanks for your help.

**Comment by bvanmieg** [comment]
I was also able to build DICe sucessfully on Ubuntu 18.04LTS (Jetson Nano - Aarch64) with the suggested swap in dice/scr/CmakeLists.txt from haemishkyd --> thanks for the suggestion!

Since Jetson Nano runs on an Aarch64 and not on intel or amd64 I had some issues with Trilinos and had to do 2 things to fix these issues:
* use the latest release of trilinos (12.14.1) to overcome an architecture error (reported here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=815725)
* modify the do-trilinos-cmake script because ubuntu 18.04 stores the blas and lapack libraries under 
/usr/lib/aarch64-linux-gnu/... instead of /usr/lib/... --> two lines needed to be modified
This is related to https://github.com/dicengine/dice/issues/81

Bart

**Comment by dicengine** [comment]
Thanks Bart!

On Aug 16, 2019, at 4:41 PM, bvanmieg <notifications@github.com<mailto:notifications@github.com>> wrote:


I was also able to build DICe sucessfully on Ubuntu 18.04LTS (Jetson Nano - Aarch64) with the suggested swap in dice/scr/CmakeLists.txt from haemishkyd --> thanks for the suggestion!

Since Jetson Nano runs on an Aarch64 and not on intel or amd64 I had some issues with Trilinos and had to do 2 things to fix these issues:

  *   use the latest release of trilinos (12.14.1) to overcome an architecture error (reported here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=815725)
  *   modify the do-trilinos-cmake script because ubuntu 18.04 stores the blas and lapack libraries under
/usr/lib/aarch64-linux-gnu/... instead of /usr/lib/... --> two lines needed to be modified
This is related to #81<https://github.com/dicengine/dice/issues/81>

Bart

**Comment by dicengine** [comment]
I made the link line swap in commit f390848

**Comment by haemishkyd** [comment]
> I made the link line swap in commit [f390848](https://github.com/dicengine/dice/commit/f390848aba8cf6dbc87953b8e21c6bdd0630d865)

Thanks. Your help was much appreciated.
