### ISSUE TITLE
Relative tolerance CTest fails

### ISSUE THREAD

**Issue by danyelizondo** [dicengine/dice#146]
Hello,

I'm compiling DICe-2.0-b15 with OpenCV-4.1.1 and Trilinos-12.10.1, under Linux Mint 19.2 (based on Ubuntu 18.04 LTS). When running the CTests, all pass except some of them related to features detection and results difference:
          42 - DICe_TestFeature (Failed)
	104 - DIFF_bitmap_star_DICe_solution_0.txt (Failed)
	194 - DIFF_stereo_d_spec_DICe_solution_0_n2 (Failed)
	195 - DIFF_stereo_d_spec_DICe_solution_0_n4 (Failed)
	196 - DIFF_stereo_d_spec_DICe_solution_1_n2 (Failed)
	197 - DIFF_stereo_d_spec_DICe_solution_1_n4 (Failed)
	198 - DIFF_stereo_d_spec_DICe_solution_2_n2 (Failed)
	199 - DIFF_stereo_d_spec_DICe_solution_2_n4 (Failed)
	200 - DIFF_stereo_d_spec_DICe_solution_3_n2 (Failed)
	201 - DIFF_stereo_d_spec_DICe_solution_3_n4 (Failed)
	202 - DIFF_stereo_d_spec_DICe_solution_4_n2 (Failed)
	203 - DIFF_stereo_d_spec_DICe_solution_4_n4 (Failed)
	204 - DIFF_stereo_d_spec_DICe_solution_5_n2 (Failed)
	205 - DIFF_stereo_d_spec_DICe_solution_5_n4 (Failed)
	208 - DIFF_stereo_dogbone_DICe_solution_0_n2 (Failed)
	209 - DIFF_stereo_dogbone_DICe_solution_0_n4 (Failed)
	210 - DIFF_stereo_dogbone_DICe_solution_1_n2 (Failed)
	211 - DIFF_stereo_dogbone_DICe_solution_1_n4 (Failed)
	212 - DIFF_stereo_dogbone_DICe_solution_2_n2 (Failed)
	213 - DIFF_stereo_dogbone_DICe_solution_2_n4 (Failed)
	214 - DIFF_stereo_dogbone_DICe_solution_3_n2 (Failed)
	215 - DIFF_stereo_dogbone_DICe_solution_3_n4 (Failed)
	216 - DIFF_stereo_dogbone_DICe_solution_4_n2 (Failed)
	217 - DIFF_stereo_dogbone_DICe_solution_4_n4 (Failed)

At least for the DIFF tests, if I reduce the relative tolerance (from 0.05 to 0.1 for d_spec or 1E-2 to 1E-1 for stereo_dogbone), the test passes. What I don't understand is, where  it comes this relative important value differences? I'm attaching the CTest verbose output log with DICE_DEBUG messages. 

Thanks for yor help,
Daniel Elizondo

[out.txt](https://github.com/dicengine/dice/files/3755472/out.txt)

**Comment by dicengine** [comment]
Hi,

It’s because the feature matching algorithm changed in OpenCV after version 3.2.0. The DICe docs need to get updated to make that clear, but if you use version 3.2.0 all the tests should pass.

-Dan


On Oct 22, 2019, at 6:17 AM, danyelizondo <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,

I'm compiling DICe-2.0-b15 with OpenCV-4.1.1 and Trilinos-12.10.1, under Linux Mint 19.2 (based on Ubuntu 18.04 LTS). When running the CTests, all pass except some of them related to features detection and results difference:
42 - DICe_TestFeature (Failed)
104 - DIFF_bitmap_star_DICe_solution_0.txt (Failed)
194 - DIFF_stereo_d_spec_DICe_solution_0_n2 (Failed)
195 - DIFF_stereo_d_spec_DICe_solution_0_n4 (Failed)
196 - DIFF_stereo_d_spec_DICe_solution_1_n2 (Failed)
197 - DIFF_stereo_d_spec_DICe_solution_1_n4 (Failed)
198 - DIFF_stereo_d_spec_DICe_solution_2_n2 (Failed)
199 - DIFF_stereo_d_spec_DICe_solution_2_n4 (Failed)
200 - DIFF_stereo_d_spec_DICe_solution_3_n2 (Failed)
201 - DIFF_stereo_d_spec_DICe_solution_3_n4 (Failed)
202 - DIFF_stereo_d_spec_DICe_solution_4_n2 (Failed)
203 - DIFF_stereo_d_spec_DICe_solution_4_n4 (Failed)
204 - DIFF_stereo_d_spec_DICe_solution_5_n2 (Failed)
205 - DIFF_stereo_d_spec_DICe_solution_5_n4 (Failed)
208 - DIFF_stereo_dogbone_DICe_solution_0_n2 (Failed)
209 - DIFF_stereo_dogbone_DICe_solution_0_n4 (Failed)
210 - DIFF_stereo_dogbone_DICe_solution_1_n2 (Failed)
211 - DIFF_stereo_dogbone_DICe_solution_1_n4 (Failed)
212 - DIFF_stereo_dogbone_DICe_solution_2_n2 (Failed)
213 - DIFF_stereo_dogbone_DICe_solution_2_n4 (Failed)
214 - DIFF_stereo_dogbone_DICe_solution_3_n2 (Failed)
215 - DIFF_stereo_dogbone_DICe_solution_3_n4 (Failed)
216 - DIFF_stereo_dogbone_DICe_solution_4_n2 (Failed)
217 - DIFF_stereo_dogbone_DICe_solution_4_n4 (Failed)

At least for the DIFF tests, if I reduce the relative tolerance (from 0.05 to 0.1 for d_spec or 1E-2 to 1E-1 for stereo_dogbone), the test passes. What I don't understand is, where it comes this relative important value differences? I'm attaching the CTest verbose output log with DICE_DEBUG messages.

Thanks for yor help,
Daniel Elizondo

out.txt<https://github.com/dicengine/dice/files/3755472/out.txt>

**Comment by danyelizondo** [comment]
Hi again,

Now compiled with OpenCV 3.2.0, and the tests passed flawlessly. Thank you! 

Daniel Elizondo
