### ISSUE TITLE
VSG strain calculation results don't match between 2D and Stereo

### ISSUE THREAD

**Issue by dandefou** [dicengine/dice#161]
Hi,

I'm having a serious issue with the calculation of VSG_STRAIN in a 3D analysis: it always tends to sub-estimate the values (roughly an order of magnitude). In order to illustrate my problem, I used the stereo_d_sample images from the Examples folder, and ran 3 analyses : 2D with left images, 2D with  right images, and a 3D. Same parameters (_subset-vased full-field_, _feature matching_, _sssig threshold_ 60, _subset size_: 39px, _step size_: 10px, _gauge size_: 30px, _gauss filter_: 7px, _calibration RMS error_ [only for 3D]: 0.328). 

Tests run with a single thread on DICe 2.0-b15 (cloned the oct-22-2019), compiled in Linux Mint 19.2 (based on Ubuntu 18.04 LTS), OpenCV 3.2.0 and Trilinos 12.10.1 (MPI enabled). CTests passed. 

Both 2D analyses showed similar results as expected. Normal strain (shape function) and VSG_STRAIN also have very close values (as expected as well). Idem for the rest of the values (displacement [in image space], strain [shape function], sigma, etc...). Nevertheless, the problem arises when I compare the VSG_STRAIN values between a 2D and the 3D results, as seen in the figure below when plotting the XX component. Same case for the YY and XY components. This sub-estimation of the strain values tends to be systematic on the analyses I've already done, only in 3D. For example, in a standardized tensile test that I recorded in stereo (files available upon request), when running a 3D analysis, the strains are also lower by a order of magnitude, in contrast with the 2D values, which shows values much closer to the theory. The rest of the results, as expected, are normal. 
![image](https://user-images.githubusercontent.com/53536843/74549553-1fefab00-4f50-11ea-9256-dee2c658419c.png)

In the log file, when running the solver, the 2D and 3D postprocessor pre_execution_tasks() seems to work well (for 2D, the coords x/y fields are COORDINATE_X/Y, and for 3D, MODEL_COORDINATES_X/Y, idem for displacement). In the DICe_PostProcessor.cpp file, I cannot see anything strange. So, I just don't understand this problem. Am I missing something? I'm attaching the input XML and the Exodus results files for the 2D and 3D analyses using the example image files. 
[2D_0.zip](https://github.com/dicengine/dice/files/4205530/2D_0.zip)
[3D.zip](https://github.com/dicengine/dice/files/4205531/3D.zip)

Any help will be greatly appreciated. 

Cheers,
Daniel Elizondo

**Comment by dicengine** [comment]
How did you define the x-axis in the stereo case?

**Comment by danyelizondo** [comment]
I didn't use the best-fit plane, so I didn't define any x-axis (I suppose it uses the left image coordinate system?). I also ran a 3D with the best-fit plane, defining the x-axis as in the YouTube tutorial, but again, same VSG results.

**Comment by dicengine** [comment]
It might be that the strain in the 2D case is calculated in terms of pixels, but in Stereo it should be in model space units.

**Comment by danyelizondo** [comment]
But, the calculation of the strain, as a dimensionless quantity, I think it should not be impacted by the use of either the SUBSET_DISPLACEMENT (in pixels for 2D case) or the MODEL_DISPLACEMENT (in physical model units for 3D case). According to the Virtual strain gauge formulation, when building **Xa = u** and **Xb = v**, the **X** matrix involves the distances between the neighbours, based on  either SUBSET_COORDINATES or MODEL_COORDINATES, for 2D and 3D respectively. Same case when fetching the **u** and **v** displacement values. So, when solving for the coefficients **a** and **b**, if the 3D calibration is good, no matters if the distances are in pixels or meters, the result should be the same. Or perhaps I'm missing something from the VSG strain definition? Should I still post-process the VSG_STRAIN results in order to compare them with experimental data? 

Thanks in advance.

**Comment by dicengine** [comment]
I should have been more specific, I mean the VSG strain window size is in pixels for the 2D case and physical space for stereo. Try adjusting the strain window size in stereo to be equivalent to the 2D case.

Now that I'm looking at the code in DICe_PostProcessor.cpp it appears the variable name in the params.xml file is strain_window_size_in_pixels, which is misleading. We will need to change the name of that variable or apply a multiplier to it to transform it from pixels to physical units for stereo.

**Comment by danyelizondo** [comment]
I followed your advise and adjusted the strain window size in physical space units (divided the initial 30 px size by 18, which is roughly the image/physical ratio) but didn't work (DICe_DEBUG : Not enough neighbours to calculate strains..). I played with different values (from 1 to 5) and same problem. I change to the other extreme, and used a huge value (400) and the results were strongly smoothed (as expected) but again under-estimated. 

I think the strain_window_size_in_pixels is not misleading in this case. When looking at the DICe DEBUG messages, the number of the neighbours used for each VSG calculation are the same in 2D and stereo (around 9 neighbours for a 30px window size, 10px step size). Furthermore, for both 2D and 3D cases, the radius neighbour search is the same (225), so, it is intriguing that during the neighbours search process, using the same radius value, it finds the same amount of neighbours (although the neighbours list in 2D should be in pixels and in stereo, they should be in physical units). Perhaps when creating the neighbourhood list, the point_cloud is still fetching the SUBSET_COORDINATES regardless of the analysis type?

**Comment by danyelizondo** [comment]
I think I see the problem: in DICe_PostProcessor.cpp, at line 267, during the pre_execution_tasks() the set_stereo_field_names() are executed _after_ the neighbourhood initialization and thus, the **coords** always uses the SUBSET_COORDINATES. That might explain why during the neighbours search, for 2D and stereo it behaves exactly the same way and also it might explain the VSG_STRAIN mismatch.

**Comment by danyelizondo** [comment]
And yes, the problem apparently is solved: I moved the set_stereo_field_names (line 267) just before the initialize_neighborhood (line 263). Now with a 2 window_size, I get the same results between the 2D and stereo:
![image](https://user-images.githubusercontent.com/53536843/74569190-1a0ebf80-4f7a-11ea-84ae-a68d09f4cce7.png)

As for the name (strain_window_size_in_pixels), you're right, is misleading. However, instead of applying a multiplier to it, perhaps for the stereo case, we can switch from radius search to k-nearest search only with the ratio of the window_size/step_size + not_so_tiny. 

Thanks for your help. I'll leave the issue open until you commit the small correction.

**Comment by dicengine** [comment]
I just saw that. Thanks for pointing this out. I'll update the code and push after I run the tests.

**Comment by dicengine** [comment]
Just a note on using a k-nearest neighbor approach, you can do that currently by setting the window size to a negative number (i.e. window size = -7.0 will use the k=7 nearest neighbors)

**Comment by danyelizondo** [comment]
Yes, you're right. We need however to change or remove this test (line 254):
`TEUCHOS_TEST_FOR_EXCEPTION(window_size_<=0,std::runtime_error,"Error, window size must be greater than 0");` perhaps testing only if `window_size_ != 0` ?

**Comment by dicengine** [comment]
Just pushed https://github.com/dicengine/dice/commit/3505fd58482549ff3e8efed4166bf22e342cbaee
to fix this
