### ISSUE TITLE
Directly use Rectified image in Stereo DIC

### ISSUE THREAD

**Issue by aakashswami** [dicengine/dice#163]
Hi,

I have the rectified images from Matlab.

How can I directly go for stereoDIC on the rectified images without the need for Cal.xml?

Because my part is highly curved and I am getting below error. 

" DICe cross-correlation initialization failed (may need to seed a nonlinear warp for this image set".

I appreciate your help! 

Thanks
Aakash

**Comment by dicengine** [comment]
Hi Aakash, There currently isn't a way to go directly to rectified images in the Stereo DIC in DICe. Getting the cross-correlation to work more robustly is something we are working on. This issue comes up frequently, especially if you have a non-planar specimen. We are experimenting with a facet projection method proposed by Helm et. al., but I don't have an estimate as to when this update would be available.

There is a way, if you are using the command line executable for DICe, to specify several sets of coordinates that match points in the left image with the right image. You will have to look at the code to figure out, but there is an example in the regression tests called stereo_satellite. I think all you have to do is create a file called projection_points.dat and list the coordinate pairs. Then in your params.xml file add a line that sets use_nonlinear_projection to true.

**Comment by aakashswami** [comment]
Thanks for your reply!
