### ISSUE TITLE
2D images calibration 

### ISSUE THREAD

**Issue by harrislboro** [dicengine/dice#173]
Hi, I have watched the tutorial videos on YouTubem and have found it very use in general. However, I am wondering if it is possible to calibrate a 2D planer image in dice. For example, a line with a known length is included in the image, as shown below. Many thanks. 
![calibrate_ohtcfrp_00-1](https://user-images.githubusercontent.com/66635788/84055400-acfdba80-a9ac-11ea-9d01-eac1c1a40952.jpg)

**Comment by dicengine** [comment]
Because of lens distortions and other issues, it's not usually very helpful to calibrate 2D DIC with a line of known length. You can do a simple pixels to physical units conversion, but not really calibrate the camera. To calibrate the camera in 2D you really need a calibration pattern with several points of known location on the pattern plate. It is possible to calibrate for 2D in DICe, but it requires images of a calibration pattern.

**Comment by harrislboro** [comment]
If I am just looking for a simple 2D DIC analysis, will I be able to do the pixels to physical units conversion in the software? Appreciate your help!

**Comment by dicengine** [comment]
Not currently
