### ISSUE TITLE
Stereo Calibration Problem: calibration image size too large, causes cal failure

### ISSUE THREAD

**Issue by Stefhu67** [dicengine/dice#192]
Hello,

I'm writing this issue because I'm currently working with DICe app on my DIC setup using two DSLR cameras. The software has some troubles detecting the points of my calibration plate. In parallel, I'm also using VIC3D that is able to perform the calibration with exactly the same pictures. I'm trying to figure out why DICe is not able while playing with the threshold and so on. If someone could help me with that, I would appreciate it. Is it also possible to have a better explanation on what the cal options are? I'm trying to compare the parameters with those of VIC3D. Please see attached a link with the calibration pictures and some screenshots to explain more my issue. 

Thanks!

https://drive.google.com/drive/folders/1dMGbOyrIwYE0dxDfDDURODjA75MRj9Al?usp=sharing

**Comment by bvanmieg** [comment]
Hi Stef,
About the calibration, I have the same problems as you have when using the installer version of DICe (2.0 beta 16). I've seen in several past threads/trials that there were issues in calibration when the image size (number of pixels) is too large. Not sure if this is fixed in the meanwhile in later releases of the build.
If you want to overcome this, you can rescale your images. Calibration just works fine if you rescale for example to 25%.

Regards,
Bart

![cal](https://user-images.githubusercontent.com/31392341/105921924-e49f9c80-6039-11eb-9922-c1dcb02420b3.png)

**Comment by Stefhu67** [comment]
Hi bvanmieg,

thank you so much, resizing files seems to work just fine for the calibration!

Regards,

Stef

**Comment by dicengine** [comment]
We should have the GUI provide a warning to the user if the image size is too big. I'm not sure what it is about OpenCV's calibration routine that causes this but we need to either warn the user or downsample the images for them. I'll leave this issue open and mark it as a bug until we sort this out. Thanks for the help Bart.

**Comment by bvanmieg** [comment]
Hi,

I did some trials with the full resolution images you provided.

In DICe_OpenCVServerUtils.cpp in line 635 the min_blob_size is hard-coded to the value 100. For large images, the script does not find the necessary 3 keypoints with this blob size. When that happens, the min_blob_size is set to 10 to try a second time, but that's even worse for large images (with large calibration dots).

I noticed that when I set the min_blob_size to 500, the calibration works for both the standard sized images as for the large images provided in this thread. I however also had to fix the threshold to 120 in the latter case to make sure it works for all images.
With adaptive threshold, this doesn't work. I could however not find the reason why this does not work when the adaptive threshold option is selected.

Instead of fixing the min_blob_size to 500, wouldn't it be an idea to define the size based on the size of the image (for example a ration of the image width)?

Bart

**Comment by dicengine** [comment]
I added a commit https://github.com/dicengine/dice/commit/40ef39b33bb9540d7ea66bac694f7fe19be3e69b that does a third pass like Bart suggested with min_blob_size of 500 if 100 or 10 don't work. This seems to address the large image calibration problems. The fix will be included in the next release of DICe, but if you want to use it now, you have to rebuild the executable.
