### ISSUE TITLE
Out-of-plane strains using virtual strain gauges?

### ISSUE THREAD

**Issue by AlexDon63** [dicengine/dice#213]
Hi,

Is there a way to include out-of-plane strain, from virtual strain gauges or otherwise, say xz, yz or zz, in the DICe solution? I tried manually adding the line, `<Parameter name="VSG_STRAIN_ZZ" type="bool" value="true" />`, to the params.xml file, then running the 3D correlation algorithm through the command line, but it looks like this line is skipped over (i.e., it is only reading VSG_STRAIN_XX, VSG_STRAIN_XY and VSG_STRAIN_YY).

Alex

**Comment by dicengine** [comment]
Hi Alex,

You are correct. You can only compute the in-plane strains using VSG in DICe.



On Jun 30, 2021, at 5:47 PM, AlexDon63 ***@***.***> wrote:

﻿

Hi,

Is there a way to include out-of-plane strain, from virtual strain gauges or otherwise, say xz, yz or zz, in the DICe solution? I tried manually adding the line, <Parameter name="VSG_STRAIN_ZZ" type="bool" value="true" />, to the params.xml file, then running the 3D correlation algorithm through the command line, but it looks like this line is skipped over (i.e., it is only reading VSG_STRAIN_XX, VSG_STRAIN_XY and VSG_STRAIN_YY).

Alex

**Comment by AlexDon63** [comment]
Thank you.

Following up on this, would there be any way to compute any z strain components through DICe? Or at least from pre-eisting DICe solution files?

**Comment by dicengine** [comment]
The only way that I'm aware of is to have stereo cameras set up on both sides of the sample, measuring the surface strains on both sides and then computing the through thickness or z strain as a post processing step. The only problem is that there is high degree of error in doing this.
