### ISSUE TITLE
Different interface

### ISSUE THREAD

**Issue by IngP96** [dicengine/dice#253]
Good morning, i just downloaded DICe and im trying to use it looking at the tutorial on yt, but i have a different interface.
I have no view control and region of interest but only IMAGE PREVIEW.
How can i fix this?

**Comment by JackL12** [comment]
I am eager to have a DICE manual, wondering if there is a link.

**Comment by dicengine** [comment]
The interface has changed slightly since the YouTube videos were made. We haven't had a chance to create some new videos with the new interface yet.

Regarding the view control, much of that was done away with in the new interface. You should see all the relevant pan and zoom tools if you put your mouse cursor near the top of the view window. 

The documentation manual for DICe is here: http://dicengine.github.io/dice/

**Comment by IngP96** [comment]
thank you so much, today i tried a few things and i found all the necessary command.
