### ISSUE TITLE
Question about coordinate system and the reconstruction results.

### ISSUE THREAD

**Issue by cxn304** [dicengine/dice#314]
Dear Dr.Turner,

I hope this email finds you well. I have a question regarding a coordinate system and the reconstruction results. In Figure 1(a), I have presented the results of my point cloud reconstruction along with the camera positions. Figure 1(b) represents the world coordinates of the camera centers. I have referred to the 'load cal file' module in the 'dice/tests/regression/stereo_rectified/cal.xml' file of the DICE repository on GitHub, which states that the camera poses in the XML file are in the world-to-camera coordinate system. Therefore, Figure 1(c) shows the poses of two cameras as mentioned in the XML file.
![1703162451944](https://github.com/dicengine/dice/assets/33156791/20f83b95-e5b8-4e34-a3a5-1df9c7f4b3bf)

Figure 1. From left to right: (a) Point cloud reconstruction results with camera positions and orientations; (b) World coordinates of camera centers; (c) Camera parameters from the XML file.

In Figure 2(a), I have selected a region of interest (ROI). Figure 2(b) displays the point cloud plot obtained by directly reading the XYZ coordinates from the 'DICe_solution_0.txt' file in the DICE's result (as described in the 'Triangulation.pdf' file, these points should be in the coordinate system of the left camera since I did not select the 'use best fit plane' option). Furthermore, Figure 3(c) shows the point cloud transformed into the world coordinate system along with the camera poses. It is evident that the point cloud plot in Figure 2(b) does not resemble a rectangular shape like the ROI in Figure 2(a); instead, it appears as a trapezoid. Moreover, it seems to deviate from the world coordinate system depicted in Figure 2(c).
![1703162486794](https://github.com/dicengine/dice/assets/33156791/f28f212f-1354-46b4-82e9-8ccde11db9a9)
Figure 2. From left to right: (a) ROI of the object; (b) plotting the point cloud from the xyz coordinates directly read from the DICe_solution_0.txt file; (c) the point cloud and camera poses after transformation to the world coordinate system.

I would greatly appreciate it if you could help me understand the reason behind this discrepancy and provide guidance on how I can rectify it.

Thank you for your attention to this matter.

**Comment by dicengine** [comment]
Hi,

It looks to me like there is a slight mistake in the camera calibration parameters, in particular the extrinsic parameters. Have you taken a look at this report: https://github.com/dicengine/dice/blob/master/doc/reports/Triangulation.pdf? That might help clarify the conventions used.

Most of the time, the issue is a simple sign convention. Here's an example that might help that was developed to get the extrinsics between two satellite imagers (GOES 16 and 17):
<img width="401" alt="Screenshot 2023-12-21 at 6 28 32 AM" src="https://github.com/dicengine/dice/assets/15202746/8efcaf53-d2f7-4921-885d-4f19b104a463">
The resulting extrinsics are:
<img width="735" alt="Screenshot 2023-12-21 at 6 28 44 AM" src="https://github.com/dicengine/dice/assets/15202746/02a71b63-3395-4745-9954-cf6ea0e27071">
If you define the extrinsics as above, you would want to set this parameter in the calibration file as well:
<Parameter name="extrinsics_relative_camera_to_camera" type="bool" value="true" />
