### ISSUE TITLE
Provide Error Message If Invalid XML files

### ISSUE THREAD

**Issue by aacruzc** [dicengine/dice#36]
Please, can you set the code to provide error message if there are non- valid xml lines.  Right now the code crashes without a warning.

Thanks.

Alvaro

**Comment by dicengine** [comment]
Turns out that none of the error reporting was making it to the terminal output on Windows (this includes incorrect XML files and even invalid parameter errors). The problem was that there wasn't any global exception catching for the main executable. This has been fixed now and DICe should be reporting all errors on exit on Windows.
