### ISSUE TITLE
Which IDE I can compiler these codes in Windows

### ISSUE THREAD

**Issue by hnsyliupeng** [dicengine/dice#42]
Sir:
    Which IDE I can compiler this codes in Windows,I should extend the function of these codes. Thanks a lot!
best wishes!

Regards
Liu

**Comment by dicengine** [comment]
Hi Lui, I'm not sure I understand exactly what your issue is about. The compilers that have been tested for compiling DICe on Windows 7 are the Intel 14 and 15 compilers as well as VS2013. As far as an IDE, we use Eclipse, but you'll have to follow their documentation for how to set the correct compiler. Let me know if that doesn't answer your question.
