### ISSUE TITLE
erros when install on ubuntu

### ISSUE THREAD

**Issue by yuguoxin** [dicengine/dice#49]
Thank you very much for your code and I love it very much.
After configuring and generating via cmake, I use sudo make to install it but errors occur like this:

[ 32%] Linking CXX executable ../../bin/dice
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libtiff.a(tif_pixarlog.o): undefined reference to symbol 'inflateEnd'
/usr/local/lib/libz.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
src/core/CMakeFiles/dice_main.dir/build.make:177: recipe for target 'bin/dice' failed
make[2]: *** [bin/dice] Error 1
CMakeFiles/Makefile2:297: recipe for target 'src/core/CMakeFiles/dice_main.dir/all' failed
make[1]: *** [src/core/CMakeFiles/dice_main.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Could you please tell me what to do next?
Thank you very much.

**Comment by dicengine** [comment]
Hi,

I’m not sure what the issue is. It could be an incompatible version of the image libraries. Or they may have been compiled with a different compiler. I would try to install you own local versions of libtiff, png, and jpeg and use the same compiler as the one you use to install DICe. That may help.

Thanks,
Dan

**Comment by dicengine** [comment]
The problem is that cmake gets the library dependency order incorrect on Ubuntu. The DICe configuration cmake files have been updated to take care of this by repeating many of the libraries in the link line. There are instructions for compiling DICe on Ubuntu here: http://dicengine.github.io/dice/#BuildingDICe. These have been tested successfully on an Ubuntu virtual machine.
