### ISSUE TITLE
invalid field name and some comments on new calibration layout

### ISSUE THREAD

**Issue by bvanmieg** [dicengine/dice#50]
Hey,

I installed the windows (10) version  release 2 beta 6. Good job with the calibration tool btw.
Is it correct that the size of the calibration target and the spacing for the markers in X and Y direction are not available anymore?
I also only see half of the right and left preview windows when scrolling down to the bottom of the page. Has this something to do with screen resolution or so?

I'm also having the following error when trying to correlate stereo images:

Output will be written to one file per frame with all subsets included
Execution information will be written to a separate file (not placed in the output headers)
Error: invalid field name requested in output spec: MODEL_COORDINATE_X
C:\Users\dzturne\Software\DICe_nightly\src\core\DICe_Schema.cpp:3325:

Throw number = 1

Throw test that evaluated to true: true

Please advise what can be wrong...

Thanks
Bart

**Comment by dicengine** [comment]
Hi Bart,

The target size does still need to be input, there’s a “pattern spacing size” field in the pattern options pane, but the number of markers in X and Y is automatically figured out from the images.

I’m not sure why you only see half of the preview windows. I would try resizing the window to see if that resets the size. Otherwise send me a screen shot so I can see what’s happening.

Regarding the MODEL_COORDINATE_X error, that’s a bug. I pushed a commit just now that fixes this and I’ve updated the installers. Thanks for catching that and let me know if you run into anything else.

Thanks,
Dan

**Comment by bvanmieg** [comment]
Hi Dan,

Thanks for the update. The bug is indeed fixed. Works without problems now.
Thanks for the clarification on the calibration pattern.
The issue with the preview windows is also solved. I can zoom in and out by pinching on my touch or by scrolling with the mouse. Untill now I always used the zoom in and out buttons in the main window and I couldn't find them in the calibration window.

Problems solved!
I'll close this issue and will let you know if I experience other weird stuff.

Bart
