### ISSUE TITLE
Ubuntu: Correlation through GUI fails but works in terminal

### ISSUE THREAD

**Issue by bvanmieg** [dicengine/dice#75]
DICe and GUI are succesfully built on Ubuntu 16.04

When trying to correlated stereo data with the GUI, I get an "Execution failed" error and reference is made to the console. The console however doesn't display relevant data about the fail (in my opinion)
The results folder is created, but I do not get any results (although the initializer, projective_trans and  projected images are created correctly).

When I then use the input, parameter and subset file that are generated by the GUI and I run the DICe code on the same images through the Ubuntu terminal, the correlation is done the right way and I get result files.

When running the same correlation in a GUI installed on windows 7 with one of the package installer, it also works without errors.

What is going wrong with the Ubuntu GUI?

I added the project folder with all relevant data to this post.

Bart
[DEBUGGING.tar.gz](https://github.com/dicengine/dice/files/1613170/DEBUGGING.tar.gz)

UPDATE 08/01/2018 --> same error when running the "stereo_d_sample" example file from the repository. The error occurs at the end of [DICe_DEBUG]: [PROC 0 of 1] processing cross correlation

**Comment by dicengine** [comment]
This issue should be fixed in the latest version of the GUI. This issue is related to the method used to spawn the dice executable process and the output buffer stream getting clogged. I changed to using child_process.spawn() instead of child_process.execFile() and it seems to work now. This was particularly bad if DICE_DEBUG_MSG was on because it produces so much output.
