### ISSUE TITLE
Throw test issue

### ISSUE THREAD

**Issue by ucgvsdr** [dicengine/dice#80]
I tried to run some sample pictures on DICE and when I run the program, DICE execution is failed and the details shown on the console as the following:

Throw number = 1

Throw test that evaluated to true: comm_->get_rank()==0&&subset_centroids_x.size()<=0

or 

Throw number = 1

Throw test that evaluated to true: num_matches < 10

Error, not enough features matched for feature matching initializer

**Comment by ucgvsdr** [comment]
Hi Bart,

Thank you for the reply. I use the installer of DICe but I did not use the
sample pictures insteaded I used my own pictures.

I just wonder if there any requirements of using the input pictures like
the resolution or size something?

Regards,
Peiying


2018年5月30日 上午6:25，"bvanmieg" <notifications@github.com>写道：

**Comment by dicengine** [comment]
Hi Guys,

Depending on your pictures, the feature matching initializer can fail if you’re using white speckles on a dark background. There are other things that would cause it to fail, but not typically due to the resolution. Can you post one of your photos?

Thanks,
Dan

On May 30, 2018, at 4:55 AM, ucgvsdr <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Bart,

Thank you for the reply. I use the installer of DICe but I did not use the
sample pictures insteaded I used my own pictures.

I just wonder if there any requirements of using the input pictures like
the resolution or size something?

Regards,
Peiying


2018年5月30日 上午6:25，"bvanmieg" <notifications@github.com<mailto:notifications@github.com>>写道：

**Comment by ucgvsdr** [comment]
Hi Dan

Since I tried to run the DICe for my upcoming project and I applied some testing pictures to see if the program works. It was a sprayed steel coupon

Regards,


发件人: Digital Image Correlation Engine (DICe)
发送时间: 2018年5月30日 8:10
收件人: dicengine/dice
抄送: ucgvsdr; Author
主题: Re: [dicengine/dice] Throw test issue (#80)

Hi Guys, 

Depending on your pictures, the feature matching initializer can fail if you’re using white speckles on a dark background. There are other things that would cause it to fail, but not typically due to the resolution. Can you post one of your photos? 

Thanks, 
Dan 

On May 30, 2018, at 4:55 AM, ucgvsdr <notifications@github.com<mailto:notifications@github.com>> wrote: 

Hi Bart, 

Thank you for the reply. I use the installer of DICe but I did not use the 
sample pictures insteaded I used my own pictures. 

I just wonder if there any requirements of using the input pictures like 
the resolution or size something? 

Regards, 
Peiying 


2018年5月30日 上午6:25，"bvanmieg" <notifications@github.com<mailto:notifications@github.com>>写道：

**Comment by dicengine** [comment]
Any chance you could post one of the pictures? That would help a lot in figuring out what's wrong.

**Comment by ucgvsdr** [comment]
![131](https://user-images.githubusercontent.com/39747152/40724909-2ad33124-63f0-11e8-9b0f-5eeb69f5c2ac.jpg)

Here is the picture

**Comment by dicengine** [comment]
My guess is that there isn’t enough contrast in the image for the default SSIG setting. The SSIG measures the amount of contrast in each subset and it prevents DICe from placing a subset where the SSIG is low. If you have the ability to change the lighting in your experiment that could help. Otherwise, I would lower the SSIG threshold in the software settings on the right hand side of the GUI. As you change the SSIG threshold, you can check where the subsets will be placed by clicking the checkmark in a circle on the upper left hand side of the GUI in the View Control box. This is the preview SSIG mask button that will display yellow circles where the SSIG threshold is good enough to place a subset.

On May 30, 2018, at 8:00 AM, ucgvsdr <notifications@github.com<mailto:notifications@github.com>> wrote:


[131]<https://user-images.githubusercontent.com/39747152/40724909-2ad33124-63f0-11e8-9b0f-5eeb69f5c2ac.jpg>

Here is the picture

**Comment by ucgvsdr** [comment]
Okay. I turned the SSIG threshold to zero and it can process the picture. 
Again, Thanks for the help.

**Comment by asteppke** [comment]
Thank you for all the work on DICE. 

I had a similar issue though, the feature matching did not work on some images with the message 

    Throw test that evaluated to true: num_matches < 10

    Error, not enough features matched for feature matching initializer

The images looked OK though and were in `.tif` format. I converted the images to `.png` and tried again. This time it all works out nicely with exactly the same settings. Is there any reason for this behavior?

**Comment by dicengine** [comment]
My guess is that the conversion from .tif to .png changed the contrast range or there is some reason within the OpenCV code that prefers the .png format. I’ll do some digging on this. Thanks for the heads up.

-Dan

On Jun 25, 2018, at 8:43 AM, asteppke <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you for all the work on DICE.

I had a similar issue though, the feature matching did not work on some images with the message

Throw test that evaluated to true: num_matches < 10

Error, not enough features matched for feature matching initializer


The images looked OK though and were in .tif format. I converted the images to .png and tried again. This time it all works out nicely with exactly the same settings. Is there any reason for this behavior?
