### ISSUE TITLE
Stereo Calibration Issues

### ISSUE THREAD

**Issue by unlusoycan** [dicengine/dice#82]
Hello,
I am using the GUI version of DICe on Windows 10. I have recordings of the calibration target provided at https://github.com/dicengine/dice/tree/master/doc/cal. 

After deactivating the images whose dots couldn't be recognized, when I click "calibrate", I receive "cal execution failed" error. 

![cal2](https://user-images.githubusercontent.com/19663471/41666518-b78086ec-7478-11e8-9b53-45aeae888012.PNG)

("not enough markers" and "pattern size couldn't be determined" messages in the console are for the images I have removed.)

I have at least 20 proper images whose dots are recognized. The program automatically creates these pictures of the target in the working directory even though it cannot make the calibration:

![cal3](https://user-images.githubusercontent.com/19663471/41666680-0aa82dd4-7479-11e8-8dce-b21c05f8da6d.png)

The cal.log file is empty. What could be causing this error? Sometimes, when I press "calibrate", I don't even receive this error - the program simply doesn't react.

Thank you.

**Comment by unlusoycan** [comment]
Hi Dan,

Thank you for your response.
I changed the directory to a folder of only the images that could be recognized. The images are all renumbered, so no missing images in the sequence. Now all the images are displayed with a green border.
Adaptive threshold is unchecked.

Unfortunately, I am still receiving the same error message. cal.log is still empty.

**Comment by dicengine** [comment]
Is there a way you could share your cal images? I’d like to see if I can re-create your problem.

Thanks,
Dan

On Jun 20, 2018, at 9:48 AM, unlusoycan <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Dan,

Thank you for your response.
I changed the directory to a folder of only the images that could be recognized. The images are all renumbered, so no missing images in the sequence. Now all the images are displayed with a green border.
Adaptive threshold is unchecked.

Unfortunately, I am still receiving the same error message. cal.log is still empty.

**Comment by unlusoycan** [comment]
Hi Dan,
You can find the images I'm using here:
https://www.dropbox.com/sh/bbftnuyu8hibd5c/AAADwTRCPnHkTX9ut0ivr2Zpa?dl=0

A thresholding constant around 39 makes all the images work.

**Comment by bvanmieg** [comment]
Hi unlusoycan,

I tried to calibrate your images on a Windows 7 DICe installation and did not experience any issues.

When deactivating adaptive threshold and setting the threshold manually to 79 (I find 39 quite low for these pictures since lower threshold values will eat away the borders of the dots and could make the automatic dot finding even more difficult) the images were all recognized and calibration was successful.
I attach the calibration results below (cal.txt). Take into account that I took 25 as the pattern spacing since I do not know what the physical distance between the dots was in your example.

I also attached the log file so you can see what it should look like. I noticed though that your epipolar error is quite high! Take care when using this calibration results.

To quickly check if the calibration went well or not, you can have a look at the tx, ty, tz values in the bottom of the calibration file. These should be the distances between your cameras taking into account the scaling of 25 as mentioned earlier.

I cannot test this on a windows 10 machine but I'm sure that Dan can help you with that.
Anyway, on windows 7 there is absolutely no issue.

Regards,
Bart

[cal.txt](https://github.com/dicengine/dice/files/2120570/cal.txt)
[cal.log](https://github.com/dicengine/dice/files/2120573/cal.log)

**Comment by dicengine** [comment]
Thanks Bart for your help. I was able to get successful cal results too using a threshold of 50 counts without adaptive thresholding turned on. This was done on a Mac, so I can’t say for Win10.

If you’re issue is solved feel free to close the issue otherwise let us know how else we can help.

Thanks,
Dan


On Jun 20, 2018, at 12:31 PM, bvanmieg <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi unlusoycan,

I tried to calibrate your images on a Windows 7 DICe installation and did not experience any issues.

When deactivating adaptive threshold and setting the threshold manually to 79 (I find 39 quite low for these pictures since lower threshold values will eat away the borders of the dots and could make the automatic dot finding even more difficult) the images were all recognized and calibration was successful.
I attach the calibration results below (cal.txt). Take into account that I took 25 as the pattern spacing since I do not know what the physical distance between the dots was in your example.

I also attached the log file so you can see what it should look like. I noticed though that your epipolar error is quite high! Take care when using this calibration results.

To quickly check if the calibration went well or not, you can have a look at the tx, ty, tz values in the bottom of the calibration file. These should be the distances between your cameras taking into account the scaling of 25 as mentioned earlier.

I cannot test this on a windows 10 machine but I'm sure that Dan can help you with that.
Anyway, on windows 7 there is absolutely no issue.

Regards,
Bart

cal.txt<https://github.com/dicengine/dice/files/2120570/cal.txt>
cal.log<https://github.com/dicengine/dice/files/2120573/cal.log>

**Comment by unlusoycan** [comment]
Dear Dan and Bart,

Thank you for your time and help. I think this was caused by some underlying issues with my installation of DICe, as I started to get an error message whenever I open DICe.

**Comment by cxn304** [comment]
I use the cal.txt as follows:
8.231909797533E+002 # cx
8.025218892045E+002 # cy
1.091752501377E+003 # fx
1.084966514792E+003 # fy
0.000000000000E+000 # fs
-2.348111559946E-001 # k1
-4.000337875932E-001 # k2
-2.570052186314E-002 # k6
8.234334966193E+002 # cx
8.027662600132E+002 # cy
1.091752501377E+003 # fx
1.084966514792E+003 # fy
0.000000000000E+000 # fs
-5.187016411549E-001 # k1
1.995256021290E-001 # k2
-5.674544109216E-001 # k6
7.984980638484E-001 # R11
-9.638027550903E-003 # R12
6.019202193442E-001 # R13
1.144721069092E-002 # R21
9.999341378828E-001 # R22
8.253871208705E-004 # R23
-6.018885307080E-001 # R31
6.231237552018E-003 # R32
7.985558016073E-001 # R33
-6.705916436959E+002 # tx
-1.813801227698E+000 # ty
2.062571296201E+002 # tz

But it give the error:C:\Users\dzturne\Software\DICe_nightly\src\core\DICe_CameraSystem.cpp:410:

Throw number = 2

Throw test that evaluated to true: total_num_values!=num_values_with_eulers&&total_num_values!=num_values_with_R

Error, invalid number of paramers in txt calibration file.
This is likely due to the text file format changing to now
require the image height and width to be specified in the file C:\Users\cxn30\Desktop\cal.txt

Could you please give the example of the cal.txt?
